const category = 'NOTIFICATION';

export const GET_NOTIFICATIONS_STARTED = `${category}__GET_NOTIFICATIONS__STARTED`;
export const GET_NOTIFICATIONS_SUCCEEDED = `${category}__GET_NOTIFICATIONS__SUCCEEDED`;
export const GET_NOTIFICATIONS_FAILED = `${category}__GET_NOTIFICATIONS__FAILED`;

export const READ_NOTIFICATION_STARTED = `${category}__READ_NOTIFICATION__STARTED`;
export const READ_NOTIFICATION_SUCCEEDED = `${category}__READ_NOTIFICATION__SUCCEEDEDE`;
export const READ_NOTIFICATION_FAILED = `${category}__READ_NOTIFICATION__FAILED`;
export const READ_NOTIFICATION_RESET = `${category}__READ_NOTIFICATION_RESET`;

export const GET_ALL_NOTIFICATION_STARTED = `${category}__GET_ALL_NOTIFICATION__STARTED`;
export const GET_ALL_NOTIFICATION_SUCCEEDED = `${category}__GET_ALL_NOTIFICATION__SUCCEEDED`;
export const GET_ALL_NOTIFICATION_FAILED = `${category}__GET_ALL_NOTIFICATION__FAILED`;

export const DELETE_NOTIFICATION_STARTED = `${category}__DELETE_NOTIFICATION__STARTED`;
export const DELETE_NOTIFICATION_SUCCEEDED = `${category}__DELETE_NOTIFICATION__SUCCEEDED`;
export const DELETE_NOTIFICATION_FAILED = `${category}__DELETE_NOTIFICATION__FAILED`;
export const RESET_DELETE_NOTIFICATION = `${category}__RESET_DELETE_NOTIFICATION`;

// MESSAGES
export const GET_MESSAGE_LOGS_STARTED = `${category}__GET_MESSAGE_LOGS__STARTED`; 
export const GET_MESSAGE_LOGS_SUCCEEDED = `${category}__GET_MESSAGE_LOGS__SUCCEEDED`; 
export const GET_MESSAGE_LOGS_FAILED = `${category}__GET_MESSAGE_LOGS__FAILED`; 

export const GET_OUTGOING_MESSAGE_LOGS_STARTED = `${category}__GET_OUTGOING_MESSAGE_LOGS__STARTED`; 
export const GET_OUTGOING_MESSAGE_LOGS_SUCCEEDED = `${category}__GET_OUTGOING_MESSAGE_LOGS__SUCCEEDED`; 
export const GET_OUTGOING_MESSAGE_LOGS_FAILED = `${category}__GET_OUTGOING_MESSAGE_LOGS__FAILED`; 

export const GET_MESSAGES_STARTED = `${category}__GET_MESSAGES__STARTED`;
export const GET_MESSAGES_SUCCEEDED = `${category}__GET_MESSAGES__SUCCEEDED`;
export const GET_MESSAGES_FAILED = `${category}__GET_MESSAGES__FAILED`;


