const category = 'NOTIFICATION';

export const GET_NOTIFICATIONS_STARTED = `${category}__GET_NOTIFICATIONS__STARTED`;
export const GET_NOTIFICATIONS_SUCCEEDED = `${category}__GET_NOTIFICATIONS__SUCCEEDED`;
export const GET_NOTIFICATIONS_FAILED = `${category}__GET_NOTIFICATIONS__FAILED`;

export const READ_NOTIFICATION_STARTED = `${category}__READ_NOTIFICATION__STARTED`;
export const READ_NOTIFICATION_SUCCEEDED = `${category}__READ_NOTIFICATION__SUCCEEDEDE`;
export const READ_NOTIFICATION_FAILED = `${category}__READ_NOTIFICATION__FAILED`;
export const READ_NOTIFICATION_RESET = `${category}__READ_NOTIFICATION_RESET`;

export const GET_ALL_NOTIFICATION_STARTED = `${category}__GET_ALL_NOTIFICATION__STARTED`;
export const GET_ALL_NOTIFICATION_SUCCEEDED = `${category}__GET_ALL_NOTIFICATION__SUCCEEDED`;
export const GET_ALL_NOTIFICATION_FAILED = `${category}__GET_ALL_NOTIFICATION__FAILED`;

export const DELETE_NOTIFICATION_STARTED = `${category}__DELETE_NOTIFICATION__STARTED`;
export const DELETE_NOTIFICATION_SUCCEEDED = `${category}__DELETE_NOTIFICATION__SUCCEEDED`;
export const DELETE_NOTIFICATION_FAILED = `${category}__DELETE_NOTIFICATION__FAILED`;
export const RESET_DELETE_NOTIFICATION = `${category}__RESET_DELETE_NOTIFICATION`;
