const category = 'NOTIFICATION';

export const GET_NOTIFICATIONS_STARTED = `${category}__GET_NOTIFICATIONS__STARTED`;
export const GET_NOTIFICATIONS_SUCCEEDED = `${category}__GET_NOTIFICATIONS__SUCCEEDED`;
export const GET_NOTIFICATIONS_FAILED = `${category}__GET_NOTIFICATIONS__FAILED`;

export const READ_NOTIFICATION_STARTED = `${category}__READ_NOTIFICATION__STARTED`;
export const READ_NOTIFICATION_SUCCEEDED = `${category}__READ_NOTIFICATION__SUCCEEDEDE`;
export const READ_NOTIFICATION_FAILED = `${category}__READ_NOTIFICATION__FAILED`;
export const READ_NOTIFICATION_RESET = `${category}__READ_NOTIFICATION_RESET`;

export const GET_ALL_NOTIFICATION_STARTED = `${category}__GET_ALL_NOTIFICATION__STARTED`;
export const GET_ALL_NOTIFICATION_SUCCEEDED = `${category}__GET_ALL_NOTIFICATION__SUCCEEDED`;
export const GET_ALL_NOTIFICATION_FAILED = `${category}__GET_ALL_NOTIFICATION__FAILED`;

export const DELETE_NOTIFICATION_STARTED = `${category}__DELETE_NOTIFICATION__STARTED`;
export const DELETE_NOTIFICATION_SUCCEEDED = `${category}__DELETE_NOTIFICATION__SUCCEEDED`;
export const DELETE_NOTIFICATION_FAILED = `${category}__DELETE_NOTIFICATION__FAILED`;
export const RESET_DELETE_NOTIFICATION = `${category}__RESET_DELETE_NOTIFICATION`;

// MESSAGES
export const GET_MESSAGE_LOGS_STARTED = `${category}__GET_MESSAGE_LOGS__STARTED`; 
export const GET_MESSAGE_LOGS_SUCCEEDED = `${category}__GET_MESSAGE_LOGS__SUCCEEDED`; 
export const GET_MESSAGE_LOGS_FAILED = `${category}__GET_MESSAGE_LOGS__FAILED`; 

export const GET_OUTGOING_MESSAGE_LOGS_STARTED = `${category}__GET_OUTGOING_MESSAGE_LOGS__STARTED`; 
export const GET_OUTGOING_MESSAGE_LOGS_SUCCEEDED = `${category}__GET_OUTGOING_MESSAGE_LOGS__SUCCEEDED`; 
export const GET_OUTGOING_MESSAGE_LOGS_FAILED = `${category}__GET_OUTGOING_MESSAGE_LOGS__FAILED`; 

export const GET_MESSAGES_STARTED = `${category}__GET_MESSAGES__STARTED`;
export const GET_MESSAGES_SUCCEEDED = `${category}__GET_MESSAGES__SUCCEEDED`;
export const GET_MESSAGES_FAILED = `${category}__GET_MESSAGES__FAILED`;

export const SEND_MESSAGE_STARTED = `${category}__SEND_MESSAGE__STARTED`;
export const SEND_MESSAGE_SUCCEEDED = `${category}__SEND_MESSAGE__SUCCEEDED`;
export const SEND_MESSAGE_FAILED = `${category}__SEND_MESSAGE__FAILED`;
export const RESET_SEND_MESSAGE_COMPLETED = `${category}__RESET_SEND_MESSAGE__COMPLETED`;

export const INCOMING_MESSAGE_DELETE_STARTED = `${category}__INCOMING_MESSAGE_DELETE_STARTED`;
export const INCOMING_MESSAGE_DELETE_SUCCEEDED = `${category}__INCOMING_MESSAGE_DELETE_SUCCEEDED`;
export const INCOMING_MESSAGE_DELETE_FAILED = `${category}__INCOMING_MESSAGE_DELETE_FAILED`;
export const RESET_INCOMING_MESSAGE_DELETE_COMPLETE = `${category}__RESET_INCOMING_MESSAGE_DELETE_COMPLETE`

export const OUTGOING_MESSAGE_DELETE_STARTED = `${category}__OUTGOING_MESSAGE_DELETE_STARTED`;
export const OUTGOING_MESSAGE_DELETE_SUCCEEDED = `${category}__OUTGOING_MESSAGE_DELETE_SUCCEEDED`;
export const OUTGOING_MESSAGE_DELETE_FAILED = `${category}__OUTGOING_MESSAGE_DELETE_FAILED`;
export const RESET_OUTGOING_MESSAGE_DELETE_COMPLETE = `${category}__RESET_OUTGOING_MESSAGE_DELETE_COMPLETE`;

export const READ_INCOMING_MESSAGE_STARTED = `${category}__READ_INCOMING_MESSAGE_STARTED`;
export const READ_INCOMING_MESSAGE_SUCCEEDED = `${category}__READ_INCOMING_MESSAGE_SUCCEEDED`;
export const READ_INCOMING_MESSAGE_FAILED = `${category}__READ_INCOMING_MESSAGE_FAILED`;
export const RESET_READ_INCOMING_MESSAGE_COMPLETE = `${category}__RESET_READ_INCOMING_MESSAGE_COMPLETE`;


