const category = 'POST';

// POST ACTIVITY LIKE
export const POST_ACTIVITY_LIKE_STARTED = `${category}__POST_ACTIVITY_LIKE__STARTED`;
export const POST_ACTIVITY_LIKE_SUCCEEDED = `${category}__POST_ACTIVITY_LIKE__SUCCEEDED`;
export const POST_ACTIVITY_LIKE_FAILED = `${category}__POST_ACTIVITY_LIKE__FAILED`;

// POST ACTIVITY FAVORITE
export const POST_ACTIVITY_FAVORITE_STARTED = `${category}__POST_ACTIVITY_FAVORITE__STARTED`;
export const POST_ACTIVITY_FAVORITE_SUCCEEDED = `${category}__POST_ACTIVITY_FAVORITE__SUCCEEDED`;
export const POST_ACTIVITY_FAVORITE_FAILED = `${category}__POST_ACTIVITY_FAVORITE__FAILED`;

// POST ACTIVITY SMILED
export const POST_ACTIVITY_SMILED_STARTED = `${category}__POST_ACTIVITY_SMILED__STARTED`;
export const POST_ACTIVITY_SMILED_SUCCEEDED = `${category}__POST_ACTIVITY_SMILED__SUCCEEDED`;
export const POST_ACTIVITY_SMILED_FAILED = `${category}__POST_ACTIVITY_SMILED__FAILED`;