const category = 'USER';

// USER LOGIN
export const USER_LOGIN_STARTED = `${category}__LOGIN_STARTED`;
export const USER_LOGIN_SUCCEEDED = `${category}__LOGIN_SUCCEEDED`;
export const USER_LOGIN_FAILED = `${category}__LOGIN_FAILED`;
export const USER_RESET_ERROR = `${category}__RESET_ERROR`;

// USER REGISTER
export const USER_REGISTER_STARTED = `${category}__USER_REGISTER__STARTED`;
export const USER_REGISTER_SUCCEEDED = `${category}__USER_REGISTER__SUCCEEDED`;
export const USER_REGISTER_FAILED = `${category}__USER_REGISTER__FAILED`;
export const USER_REGISTER_COMPLETED_RESET = `${category}__USER_REGISTER_COMPLETED_RESET`;

// USER POST LIST
export const USER_POST_LIST_STARTED = `${category}__USER_POST_LIST__STARTED`;
export const USER_POST_LIST_SUCCEEDED = `${category}__USER_POST_LIST__SUCCEEDED`;
export const USER_POST_LIST_FAILED = `${category}__USER_POST_LIST__FAILED`;

//USER CREATE POST
export const USER_CREATE_POST_STARTED = `${category}__USER_CREATE_POST__STARTED`;
export const USER_CREATE_POST_SUCCEEDED = `${category}__USER_CREATE_POST__SUCCEEDED`;
export const USER_CREATE_POST_FAILED = `${category}__USER_CREATE_POST__FAILED`;
export const RESET_CREATE_POST_COMPLETE = `${category}__RESET_CREATE_POST_COMPLETE`;

// USER UPLOAD PROFILE PHOTO
export const USER_UPLOAD_PROFILE_PHOTO_STARTED = `${category}__USER_UPLOAD_PROFILE_PHOTO__STARTED`;
export const USER_UPLOAD_PROFILE_PHOTO_SUCCEEDED = `${category}__USER_UPLOAD_PROFILE_PHOTO__SUCCEEDED`;
export const USER_UPLOAD_PROFILE_PHOTO_FAILED = `${category}__USER_UPLOAD_PROFILE_PHOTO__FAILED`;
export const RESET_UPLOAD_PROFILE_PHOTO_COMPLETE = `${category}__RESET_UPLOAD_PROFILE_PHOTO__COMPLETE`;

// GET USER ME
export const GET_USER_ME_STARTED = `${category}__GET_USER_ME__STARTED`;
export const GET_USER_ME_SUCCEEDED = `${category}__GET_USER_ME__SUCCEEDED`;
export const GET_USER_ME_FAILED = `${category}__GET_USER_ME__FAILED`;

// UPDATE PERSONAL INFORMATION
export const UPDATE_USER_PERSONAL_INFO_STARTED = `${category}__UPDATE_USER_PERSONAL_INFO__STARTED`;
export const UPDATE_USER_PERSONAL_INFO_SUCCEEDED = `${category}__UPDATE_USER_PERSONAL_INFO__SUCCEEDED`;
export const UPDATE_USER_PERSONAL_INFO_FAILED = `${category}__UPDATE_USER_PERSONAL_INFO__FAILED`;
export const RESET_UPDATE_USER_PERSONAL_INFO_COMPLETE = `${category}__RESET_UPDATE_USER_PERSONAL_INFO_COMPLETE`;

// GET USERS
export const GET_USERS_STARTED = `${category}__GET_USERS__STARTED`;
export const GET_USERS_SUCCEEDED = `${category}__GET_USERS__SUCCEEDED`;
export const GET_USERS_FAILED = `${category}__GET_USERS__FAILED`;

// GET MY FAVORITE USERS
export const GET_MY_FAVORITE_USERS_STARTED = `${category}__GET_MY_FAVORITE_USERS__STARTED`;
export const GET_MY_FAVORITE_USERS_SUCCEEDED = `${category}__GET_MY_FAVORITE_USERS__SUCCEEDED`;
export const GET_MY_FAVORITE_USERS_FAILED = `${category}__GET_MY_FAVORITE_USERS__FAILED`;
