const category = 'USER';

// USER LOGIN
export const USER_LOGIN_STARTED = `${category}__LOGIN_STARTED`;
export const USER_LOGIN_SUCCEEDED = `${category}__LOGIN_SUCCEEDED`;
export const USER_LOGIN_FAILED = `${category}__LOGIN_FAILED`;
export const USER_RESET_ERROR = `${category}__RESET_ERROR`;

// USER REGISTER
export const USER_REGISTER_STARTED = `${category}__USER_REGISTER__STARTED`;
export const USER_REGISTER_SUCCEEDED = `${category}__USER_REGISTER__SUCCEEDED`;
export const USER_REGISTER_FAILED = `${category}__USER_REGISTER__FAILED`;
export const USER_REGISTER_COMPLETED_RESET = `${category}__USER_REGISTER_COMPLETED_RESET`;

// USER POST LIST
export const USER_POST_LIST_STARTED = `${category}__USER_POST_LIST__STARTED`;
export const USER_POST_LIST_SUCCEEDED = `${category}__USER_POST_LIST__SUCCEEDED`;
export const USER_POST_LIST_FAILED = `${category}__USER_POST_LIST__FAILED`;

//USER CREATE POST
export const USER_CREATE_POST_STARTED = `${category}__USER_CREATE_POST__STARTED`;
export const USER_CREATE_POST_SUCCEEDED = `${category}__USER_CREATE_POST__SUCCEEDED`;
export const USER_CREATE_POST_FAILED = `${category}__USER_CREATE_POST__FAILED`;
export const RESET_CREATE_POST_COMPLETE = `${category}__RESET_CREATE_POST_COMPLETE`;

// USER UPLOAD PROFILE PHOTO
export const USER_UPLOAD_PROFILE_PHOTO_STARTED = `${category}__USER_UPLOAD_PROFILE_PHOTO__STARTED`;
export const USER_UPLOAD_PROFILE_PHOTO_SUCCEEDED = `${category}__USER_UPLOAD_PROFILE_PHOTO__SUCCEEDED`;
export const USER_UPLOAD_PROFILE_PHOTO_FAILED = `${category}__USER_UPLOAD_PROFILE_PHOTO__FAILED`;
export const RESET_UPLOAD_PROFILE_PHOTO_COMPLETE = `${category}__RESET_UPLOAD_PROFILE_PHOTO__COMPLETE`;

// GET USER ME
export const GET_USER_ME_STARTED = `${category}__GET_USER_ME__STARTED`;
export const GET_USER_ME_SUCCEEDED = `${category}__GET_USER_ME__SUCCEEDED`;
export const GET_USER_ME_FAILED = `${category}__GET_USER_ME__FAILED`;

// UPDATE PERSONAL INFORMATION
export const UPDATE_USER_PERSONAL_INFO_STARTED = `${category}__UPDATE_USER_PERSONAL_INFO__STARTED`;
export const UPDATE_USER_PERSONAL_INFO_SUCCEEDED = `${category}__UPDATE_USER_PERSONAL_INFO__SUCCEEDED`;
export const UPDATE_USER_PERSONAL_INFO_FAILED = `${category}__UPDATE_USER_PERSONAL_INFO__FAILED`;
export const RESET_UPDATE_USER_PERSONAL_INFO_COMPLETE = `${category}__RESET_UPDATE_USER_PERSONAL_INFO_COMPLETE`;

// GET USERS
export const GET_USERS_STARTED = `${category}__GET_USERS__STARTED`;
export const GET_USERS_SUCCEEDED = `${category}__GET_USERS__SUCCEEDED`;
export const GET_USERS_FAILED = `${category}__GET_USERS__FAILED`;

// GET MY FAVORITE USERS
export const GET_MY_FAVORITE_USERS_STARTED = `${category}__GET_MY_FAVORITE_USERS__STARTED`;
export const GET_MY_FAVORITE_USERS_SUCCEEDED = `${category}__GET_MY_FAVORITE_USERS__SUCCEEDED`;
export const GET_MY_FAVORITE_USERS_FAILED = `${category}__GET_MY_FAVORITE_USERS__FAILED`;

// MY MY SMILED USERS
export const GET_MY_SMILED_PROFILES_STARTED = `${category}__GET_MY_SMILED_PROFILES__STARTED`;
export const GET_MY_SMILED_PROFILES_SUCCEEDED = `${category}__GET_MY_SMILED_PROFILES__SUCCEEDED`;
export const GET_MY_SMILED_PROFILES_FAILED = `${category}__GET_MY_SMILED_PROFILES__FAILED`;

// GET MY LIKED USERS
export const GET_MY_LIKED_PROFILES_STARTED = `${category}__GET_MY_LIKED_PROFILES__STARTED`;
export const GET_MY_LIKED_PROFILES_SUCCEEDED = `${category}__GET_MY_LIKED_PROFILES__SUCCEEDED`;
export const GET_MY_LIKED_PROFILES_FAILED = `${category}__GET_MY_LIKED_PROFILES__FAILED`;

// GET MY BLOCKED USERS
export const GET_MY_BLOCKED_PROFILES_STARTED = `${category}__GET_MY_BLOCKED_PROFILES__STARTED`;
export const GET_MY_BLOCKED_PROFILES_SUCCEEDED = `${category}__GET_MY_BLOCKED_PROFILES__SUCCEEDED`;
export const GET_MY_BLOCKED_PROFILES_FAILED = `${category}__GET_MY_BLOCKED_PROFILES__FAILED`;

// GET ONLINE PROFILES
export const GET_ONLINE_PROFILES_STARTED = `${category}__GET_ONLINE_PROFILES_STARTED`;
export const GET_ONLINE_PROFILES_SUCCEEDED = `${category}__GET_ONLINE_PROFILES_SUCCEEDED`;
export const GET_ONLINE_PROFILES_FAILED = `${category}__GET_ONLINE_PROFILES_FAILED`;

// USER ACTIVITY LIKED
export const USER_ACTIVITY_LIKED_STARTED = `${category}__USER_ACTIVITY_LIKED__STARTED`;
export const USER_ACTIVITY_LIKED_SUCCEEDED = `${category}__USER_ACTIVITY_LIKED__SUCCEEDED`;
export const USER_ACTIVITY_LIKED_FAILED = `${category}__USER_ACTIVITY_LIKED__FAILED`;
export const USER_ACTIVITY_LIKED_RESET = `${category}__USER_ACTIVITY_LIKED_RESET`;

// USER ACTIVITY FAVORITE
export const USER_ACTIVITY_FAVORITE_STARTED = `${category}__USER_ACTIVITY_FAVORITE__STARTED`;
export const USER_ACTIVITY_FAVORITE_SUCCEEDED = `${category}__USER_ACTIVITY_FAVORITE__SUCCEEDED`;
export const USER_ACTIVITY_FAVORITE_FAILED = `${category}__USER_ACTIVITY_FAVORITE__FAILED`;
export const USER_ACTIVITY_FAVORITE_RESET = `${category}__USER_ACTIVITY_FAVORITE__RESET`;

// USER ACTIVITY SMILED
export const USER_ACTIVITY_SMILED_STARTED = `${category}__USER_ACTIVITY_SMILED__STARTED`;
export const USER_ACTIVITY_SMILED_SUCCEEDED = `${category}__USER_ACTIVITY_SMILED__SUCCEEDED`;
export const USER_ACTIVITY_SMILED_FAILED = `${category}__USER_ACTIVITY_SMILED__FAILED`;
export const USER_ACTIVITY_SMILED_RESET = `${category}__USER_ACTIVITY_SMILED_RESET`;

// USER BLOCKED
export const USER_BLOCKED_STARTED = `${category}__USER_BLOCKED__STARTED`;
export const USER_BLOCKED_SUCCEEDED = `${category}__USER_BLOCKED__SUCCEEDED`;
export const USER_BLOCKED_FAILED = `${category}__USER_BLOCKED__FAILED`;
export const USER_BLOCKED_RESET = `${category}__USER_BLOCKED_RESET`;

// USER REPORT
export const USER_REPORTS_STARTED = `${category}__USER_REPORTS__STARTED`;
export const USER_REPORTS_SUCCEEDED = `${category}__USER_REPORTS__SUCCEEDED`;
export const USER_REPORTS_FAILED = `${category}__USER_REPORTS__FAILED`;
export const USER_REPORTS_RESET = `${category}__USER_REPORTS__RESET`;

// USER UPDATE SPOUSE CANDIDATE
export const USER_UPDATE_SPOUSE_CANDIDATE_STARTED = `${category}__USER_UPDATE_SPOUSE_CANDIDATE__STARTED`;
export const USER_UPDATE_SPOUSE_CANDIDATE_SUCCEEDED = `${category}__USER_UPDATE_SPOUSE_CANDIDATE__SUCCEEDED`;
export const USER_UPDATE_SPOUSE_CANDIDATE_FAILED = `${category}__USER_UPDATE_SPOUSE_CANDIDATE__FAILED`;
export const USER_UPDATE_SPOUSE_CANIDATE_RESET = `${category}__USER_UPDATE_SPOUSE_CANDIDATE_RESET`;

// USER UPDATE CARACTERISTIC FEATURE
export const USER_UPDATE_CARACTERISTIC_FEATURE_STARTED = `${category}__USER_UPDATE_CARACTERISTIC_FEATURE__STARTED`;
export const USER_UPDATE_CARACTERISTIC_FEATURE_SUCCEEDED = `${category}__USER_UPDATE_CARACTERISTIC_FEATURE__SUCCEEDED`;
export const USER_UPDATE_CARACTERISTIC_FEATURE_FAILED = `${category}__USER_UPDATE_CARACTERISTIC_FEATURE__FAILED`;
export const USER_UPDATE_CARACTERISTIC_FEATURE_RESET = `${category}__USER_UPDATE_CARACTERISTIC_FEATURE_RESET`;
