const category = 'USER';

// USER LOGIN
export const USER_LOGIN_STARTED = `${category}__LOGIN_STARTED`;
export const USER_LOGIN_SUCCEEDED = `${category}__LOGIN_SUCCEEDED`;
export const USER_LOGIN_FAILED = `${category}__LOGIN_FAILED`;
export const USER_RESET_ERROR = `${category}__RESET_ERROR`;

// USER REGISTER
export const USER_REGISTER_STARTED = `${category}__USER_REGISTER__STARTED`;
export const USER_REGISTER_SUCCEEDED = `${category}__USER_REGISTER__SUCCEEDED`;
export const USER_REGISTER_FAILED = `${category}__USER_REGISTER__FAILED`;
export const USER_REGISTER_COMPLETED_RESET = `${category}__USER_REGISTER_COMPLETED_RESET`;

// USER POST LIST
export const USER_POST_LIST_STARTED = `${category}__USER_POST_LIST__STARTED`;
export const USER_POST_LIST_SUCCEEDED = `${category}__USER_POST_LIST__SUCCEEDED`;
export const USER_POST_LIST_FAILED = `${category}__USER_POST_LIST__FAILED`;

//USER CREATE POST
export const USER_CREATE_POST_STARTED = `${category}__USER_CREATE_POST__STARTED`;
export const USER_CREATE_POST_SUCCEEDED = `${category}__USER_CREATE_POST__SUCCEEDED`;
export const USER_CREATE_POST_FAILED = `${category}__USER_CREATE_POST__FAILED`;
export const RESET_CREATE_POST_COMPLETE = `${category}__RESET_CREATE_POST_COMPLETE`;

// USER UPLOAD PROFILE PHOTO
export const USER_UPLOAD_PROFILE_PHOTO_STARTED = `${category}__USER_UPLOAD_PROFILE_PHOTO__STARTED`;
export const USER_UPLOAD_PROFILE_PHOTO_SUCCEEDED = `${category}__USER_UPLOAD_PROFILE_PHOTO__SUCCEEDED`;
export const USER_UPLOAD_PROFILE_PHOTO_FAILED = `${category}__USER_UPLOAD_PROFILE_PHOTO__FAILED`;
export const RESET_UPLOAD_PROFILE_PHOTO_COMPLETE = `${category}__RESET_UPLOAD_PROFILE_PHOTO__COMPLETE`;

// GET USER ME
export const GET_USER_ME_STARTED = `${category}__GET_USER_ME__STARTED`;
export const GET_USER_ME_SUCCEEDED = `${category}__GET_USER_ME__SUCCEEDED`;
export const GET_USER_ME_FAILED = `${category}__GET_USER_ME__FAILED`;

// UPDATE PERSONAL INFORMATION
export const UPDATE_USER_PERSONAL_INFO_STARTED = `${category}__UPDATE_USER_PERSONAL_INFO__STARTED`;
export const UPDATE_USER_PERSONAL_INFO_SUCCEEDED = `${category}__UPDATE_USER_PERSONAL_INFO__SUCCEEDED`;
export const UPDATE_USER_PERSONAL_INFO_FAILED = `${category}__UPDATE_USER_PERSONAL_INFO__FAILED`;
export const RESET_UPDATE_USER_PERSONAL_INFO_COMPLETE = `${category}__RESET_UPDATE_USER_PERSONAL_INFO_COMPLETE`;

// GET USERS
export const GET_USERS_STARTED = `${category}__GET_USERS__STARTED`;
export const GET_USERS_SUCCEEDED = `${category}__GET_USERS__SUCCEEDED`;
export const GET_USERS_FAILED = `${category}__GET_USERS__FAILED`;

// GET APPROVE USERS
export const GET_APPROVE_USERS_STARTED = `${category}__GET_APPROVE_USERS__STARTED`;
export const GET_APPROVE_USERS_SUCCEEDED = `${category}__GET_APPROVE_USERS__SUCCEEDED`;
export const GET_APPROVE_USERS_FAILED = `${category}__GET_APPROVE_USERS__FAILED`;

// GET MY FAVORITE USERS
export const GET_MY_FAVORITE_USERS_STARTED = `${category}__GET_MY_FAVORITE_USERS__STARTED`;
export const GET_MY_FAVORITE_USERS_SUCCEEDED = `${category}__GET_MY_FAVORITE_USERS__SUCCEEDED`;
export const GET_MY_FAVORITE_USERS_FAILED = `${category}__GET_MY_FAVORITE_USERS__FAILED`;

// MY MY SMILED USERS
export const GET_MY_SMILED_PROFILES_STARTED = `${category}__GET_MY_SMILED_PROFILES__STARTED`;
export const GET_MY_SMILED_PROFILES_SUCCEEDED = `${category}__GET_MY_SMILED_PROFILES__SUCCEEDED`;
export const GET_MY_SMILED_PROFILES_FAILED = `${category}__GET_MY_SMILED_PROFILES__FAILED`;

// GET MY LIKED USERS
export const GET_MY_LIKED_PROFILES_STARTED = `${category}__GET_MY_LIKED_PROFILES__STARTED`;
export const GET_MY_LIKED_PROFILES_SUCCEEDED = `${category}__GET_MY_LIKED_PROFILES__SUCCEEDED`;
export const GET_MY_LIKED_PROFILES_FAILED = `${category}__GET_MY_LIKED_PROFILES__FAILED`;

// GET MY BLOCKED USERS
export const GET_MY_BLOCKED_PROFILES_STARTED = `${category}__GET_MY_BLOCKED_PROFILES__STARTED`;
export const GET_MY_BLOCKED_PROFILES_SUCCEEDED = `${category}__GET_MY_BLOCKED_PROFILES__SUCCEEDED`;
export const GET_MY_BLOCKED_PROFILES_FAILED = `${category}__GET_MY_BLOCKED_PROFILES__FAILED`;

// GET ONLINE PROFILES
export const GET_ONLINE_PROFILES_STARTED = `${category}__GET_ONLINE_PROFILES_STARTED`;
export const GET_ONLINE_PROFILES_SUCCEEDED = `${category}__GET_ONLINE_PROFILES_SUCCEEDED`;
export const GET_ONLINE_PROFILES_FAILED = `${category}__GET_ONLINE_PROFILES_FAILED`;

// USER ACTIVITY LIKED
export const USER_ACTIVITY_LIKED_STARTED = `${category}__USER_ACTIVITY_LIKED__STARTED`;
export const USER_ACTIVITY_LIKED_SUCCEEDED = `${category}__USER_ACTIVITY_LIKED__SUCCEEDED`;
export const USER_ACTIVITY_LIKED_FAILED = `${category}__USER_ACTIVITY_LIKED__FAILED`;
export const USER_ACTIVITY_LIKED_RESET = `${category}__USER_ACTIVITY_LIKED_RESET`;

// USER ACTIVITY FAVORITE
export const USER_ACTIVITY_FAVORITE_STARTED = `${category}__USER_ACTIVITY_FAVORITE__STARTED`;
export const USER_ACTIVITY_FAVORITE_SUCCEEDED = `${category}__USER_ACTIVITY_FAVORITE__SUCCEEDED`;
export const USER_ACTIVITY_FAVORITE_FAILED = `${category}__USER_ACTIVITY_FAVORITE__FAILED`;
export const USER_ACTIVITY_FAVORITE_RESET = `${category}__USER_ACTIVITY_FAVORITE__RESET`;

// USER ACTIVITY SMILED
export const USER_ACTIVITY_SMILED_STARTED = `${category}__USER_ACTIVITY_SMILED__STARTED`;
export const USER_ACTIVITY_SMILED_SUCCEEDED = `${category}__USER_ACTIVITY_SMILED__SUCCEEDED`;
export const USER_ACTIVITY_SMILED_FAILED = `${category}__USER_ACTIVITY_SMILED__FAILED`;
export const USER_ACTIVITY_SMILED_RESET = `${category}__USER_ACTIVITY_SMILED_RESET`;

// USER BLOCKED
export const USER_BLOCKED_STARTED = `${category}__USER_BLOCKED__STARTED`;
export const USER_BLOCKED_SUCCEEDED = `${category}__USER_BLOCKED__SUCCEEDED`;
export const USER_BLOCKED_FAILED = `${category}__USER_BLOCKED__FAILED`;
export const USER_BLOCKED_RESET = `${category}__USER_BLOCKED_RESET`;

// USER REPORT
export const USER_REPORTS_STARTED = `${category}__USER_REPORTS__STARTED`;
export const USER_REPORTS_SUCCEEDED = `${category}__USER_REPORTS__SUCCEEDED`;
export const USER_REPORTS_FAILED = `${category}__USER_REPORTS__FAILED`;
export const USER_REPORTS_RESET = `${category}__USER_REPORTS__RESET`;

// USER UPDATE SPOUSE CANDIDATE
export const USER_UPDATE_SPOUSE_CANDIDATE_STARTED = `${category}__USER_UPDATE_SPOUSE_CANDIDATE__STARTED`;
export const USER_UPDATE_SPOUSE_CANDIDATE_SUCCEEDED = `${category}__USER_UPDATE_SPOUSE_CANDIDATE__SUCCEEDED`;
export const USER_UPDATE_SPOUSE_CANDIDATE_FAILED = `${category}__USER_UPDATE_SPOUSE_CANDIDATE__FAILED`;
export const USER_UPDATE_SPOUSE_CANIDATE_RESET = `${category}__USER_UPDATE_SPOUSE_CANDIDATE_RESET`;

// USER UPDATE CARACTERISTIC FEATURE
export const USER_UPDATE_CARACTERISTIC_FEATURE_STARTED = `${category}__USER_UPDATE_CARACTERISTIC_FEATURE__STARTED`;
export const USER_UPDATE_CARACTERISTIC_FEATURE_SUCCEEDED = `${category}__USER_UPDATE_CARACTERISTIC_FEATURE__SUCCEEDED`;
export const USER_UPDATE_CARACTERISTIC_FEATURE_FAILED = `${category}__USER_UPDATE_CARACTERISTIC_FEATURE__FAILED`;
export const USER_UPDATE_CARACTERISTIC_FEATURE_RESET = `${category}__USER_UPDATE_CARACTERISTIC_FEATURE_RESET`;

// GET MY POSTS
export const GET_MY_POSTS_STARTED = `${category}__GET_MY_POSTS__STARTED`;
export const GET_MY_POSTS_SUCCEEDED = `${category}__GET_MY_POSTS__SUCCEEDED`;
export const GET_MY_POSTS_FAILED = `${category}__GET_MY_POSTS__FAILED`;

// CREATE USER PROFILE VISIT LOG
export const CREATE_USER_PROFILE_VISIT_LOG_STARTED = `${category}__CREATE_USER_PROFILE_VISIT_LOG__STARTED`;
export const CREATE_USER_PROFILE_VISIT_LOG_SUCCEEDED = `${category}__CREATE_USER_PROFILE_VISIT_LOG__SUCCEEDED`;
export const CREATE_USER_PROFILE_VISIT_LOG_FAILED = `${category}__CREATE_USER_PROFILE_VISIT_LOG__FAILED`;

// GET USER PROFILE VISIT
export const GET_USER_PROFILE_VISIT_STARTED = `${category}__GET_USER_PROFILE_VISIT__STARTED`;
export const GET_USER_PROFILE_VISIT_SUCCEEDED = `${category}__GET_USER_PROFILE_VISIT__SUCCEEDED`;
export const GET_USER_PROFILE_VISIT_FAILED = `${category}__GET_USER_PROFILE_VISIT__FAILED`;

// GET USER MATCH
export const GET_USER_MATCH_STARTED = `${category}__GET_USER_MATCH__STARTED`;
export const GET_USER_MATCH_SUCCEEDED = `${category}__GET_USER_MATCH__SUCCEEDED`;
export const GET_USER_MATCH_FAILED = `${category}__GET_USER_MATCH__FAILED`;
export const RESET_USER_MATCH = `${category}__RESET_USER_MATCH`;

// GET MATCH PREVIUS USER
export const GET_MATCH_PREVIUS_USER_STARTED = `${category}__GET_MATCH_PREVIUS_USER__STARTED`;
export const GET_MATCH_PREVIUS_USER_SUCCEEDED = `${category}__GET_MATCH_PREVIUS_USER__SUCCEEDED`;
export const GET_MATCH_PREVIUS_USER_FAILED = `${category}__GET_MATCH_PREVIUS_USER__FAILED`;
export const RESET_MATCH_PREVIUS_USER = `${category}__RESET_MATCH_PREVIUS_USER`;

export const USER_LOGOUT_STARTED = `${category}__USER_LOGOUT__STARTED`;
export const USER_LOGOUT_SUCCEEDED = `${category}__USER_LOGOUT__SUCCEEDED`;
export const USER_LOGOUT_FAILED = `${category}__USER_LOGOUT__FAILED`;

export const GET_STORY_STARTED = `${category}__GET_STORY_STARTED`;
export const GET_STORY_SUCCEEDED = `${category}__GET_STORY_SUCCEEDED`;
export const GET_STORY_FAILED = `${category}__GET_STORY_FAILED`;

export const GET_MY_STORY_STARTED = `${category}__GET_MY_STORY__STARTED`;
export const GET_MY_STORY_SUCCEEDED = `${category}__GET_MY_STORY__SUCCEEDED`;
export const GET_MY_STORY_FAILED = `${category}__GET_MY_STORY__FAILED`;

export const CREATE_STORY_STARTED = `${category}__CREATE_STORY__STARTED`;
export const CREATE_STORY_SUCCEEDED = `${category}__CREATE_STORY__SUCCEEDED`;
export const CREATE_STORY_FAILED = `${category}__CREATE_STORY_FAILED`;
export const RESET_CREATE_STORY_COMPLETE =  `${category}__RESET_CREATE_STORY_COMPLETE`;

export const USER_UPLOAD_PHOTO_STARTED = `${category}__USER_UPLOAD_PHOTO__STARTED`;
export const USER_UPLOAD_PHOTO_SUCCEEDED = `${category}__USER_UPLOAD_PHOTO__SUCCEEDED`;
export const USER_UPLOAD_PHOTO_FAILED = `${category}__USER_UPLOAD_PHOTO__FAILED`;

export const GET_USER_PHOTO_STARTED = `${category}__GET_USER_PHOTO__STARTED`;
export const GET_USER_PHOTO_SUCCEEDED = `${category}__GET_USER_PHOTO__SUCCEEDED`;
export const GET_USER_PHOTO_FAILED = `${category}__GET_USER_PHOTO__FAILED`;

export const USER_FREEZE_ACCOUNT_STARTED = `${category}__USER_FREEZE_ACCOUNT__STARTED`;
export const USER_FREEZE_ACCOUNT_SUCCEEDED = `${category}__USER_FREEZE_ACCOUNT__SUCCEEDED`;
export const USER_FREEZE_ACCOUNT_FAILED = `${category}__USER_FREEZE_ACCOUNT__FAILED`;
export const RESET_USER_FREEZE_ACCOUNT_COMPLETE = `${category}__RESET_USER_FREEZE_ACCOUNT_COMPLETE`;

export const USER_DELETE_ACCOUNT_STARTED = `${category}__USER_DELETE_ACCOUNT__STARTED`;
export const USER_DELETE_ACCOUNT_SUCCEEDED = `${category}__USER_DELETE_ACCOUNT__SUCCEEDED`;
export const USER_DELETE_ACCOUNT_FAILED = `${category}__USER_DELETE_ACCOUNT__FAILED`;
export const RESET_USER_DELETE_ACCOUNT_COMPLETE = `${category}__RESET_USER_DELETE_ACCOUNT_COMPLETE`;

export const USER_CHANGE_EMAIL_STARTED = `${category}__USER_CHANGE_EMAIL__STARTED`;
export const USER_CHANGE_EMAIL_SUCCEEDED = `${category}__USER_CHANGE_EMAIL__SUCCEEDED`;
export const USER_CHANGE_EMAIL_FAILED = `${category}__USER_CHANGE_EMAIL__FAILED`;
export const RESET_USER_CHANGE_EMAIL_COMPLETE = `${category}__RESET_USER_CHANGE_EMAIL_COMPLETE`;

export const USER_CHANGE_PASSWORD_STARTED = `${category}__USER_CHANGE_PASSWORD__STARTED`;
export const USER_CHANGE_PASSWORD_SUCCEEDED = `${category}__USER_CHANGE_PASSWORD__SUCCEEDED`;
export const USER_CHANGE_PASSWORD_FAILED = `${category}__USER_CHANGE_PASSWORD__FAILED`;
export const RESET_USER_CHANGE_PASSWORD_COMPLETE = `${category}__RESET_USER_CHANGE_PASSWORD_COMPLETE`;

export const CREATE_PAYMENT_STARTED = `${category}__CREATE_PAYMENT__STARTED`;
export const CREATE_PAYMENT_SUCCEEDED = `${category}__CREATE_PAYMENT__SUCCEEDED`;
export const CREATE_PAYMENT_FAILED = `${category}__CREATE_PAYMENT__FAILED`;
export const RESET_CREATE_PAYMENT_COMPLETE = `${category}__RESET_CREATE_PAYMENT_COMPLETE`;

// ADMIN GET USERS
export const ADMIN_GET_USERS_STARTED = `${category}__ADMIN_GET_USERS__STARTED`;
export const ADMIN_GET_USERS_SUCCEEDED = `${category}__ADMIN_GET_USERS__SUCCEEDED`;
export const ADMIN_GET_USERS_FAILED = `${category}__ADMIN_GET_USERS__FAILED`;

// ADMIN GET USER DETAILS
export const ADMIN_GET_USER_DETAILS_STARTED = `${category}__ADMIN_GET_USER_DETAILS__STARTED`;
export const ADMIN_GET_USER_DETAILS_SUCCEEDED = `${category}__ADMIN_GET_USER_DETAILS__SUCCEEDED`;
export const ADMIN_GET_USER_DETAILS_FAILED = `${category}__ADMIN_GET_USER_DETAILS__FAILED`;

// ADMIN DELETE USER
export const ADMIN_DELETE_USER_STARTED = `${category}__ADMIN_DELETE_USER__STARTED`;
export const ADMIN_DELETE_USER_SUCCEEDED = `${category}__ADMIN_DELETE_USER__SUCCEEDED`;
export const ADMIN_DELETE_USER_FAILED = `${category}__ADMIN_DELETE_USER__FAILED`;
export const ADMIN_DELETE_USER_RESET = `${category}__ADMIN_DELETE_USER_RESET`;

// GET STORIES
export const ADMIN_GET_STORIES_STARTED = `${category}__ADMIN_GET_STORIES__STARTED`;
export const ADMIN_GET_STORIES_SUCCEEDED = `${category}__ADMIN_GET_STORIES__SUCCEEDED`;
export const ADMIN_GET_STORIES_FAILED = `${category}__ADMIN_GET_STORIES__FAILED`;

// APPROVE STORY
export const ADMIN_APPROVE_STORY_STARTED = `${category}__ADMIN_APPROVE_STORY__STARTED`;
export const ADMIN_APPROVE_STORY_SUCCEEDED = `${category}__ADMIN_APPROVE_STORY__SUCCEEDED`;
export const ADMIN_APPROVE_STORY_FAILED = `${category}__ADMIN_APPROVE_STORY__FAILED`;
export const ADMIN_APPROVE_STORY_RESET = `${category}__ADMIN_APPROVE_STORY__RESET`;

// GET PHOTOS
export const ADMIN_GET_PHOTOS_STARTED = `${category}__ADMIN_GET_PHOTOS__STARTED`;
export const ADMIN_GET_PHOTOS_SUCCEEDED = `${category}__ADMIN_GET_PHOTOS__SUCCEEDED`;
export const ADMIN_GET_PHOTOS_FAILED = `${category}__ADMIN_GET_PHOTOS__FAILED`;

// APPROVE PHOTO
export const ADMIN_APPROVE_PHOTO_STARTED = `${category}__ADMIN_APPROVE_PHOTO__STARTED`;
export const ADMIN_APPROVE_PHOTO_SUCCEEDED = `${category}__ADMIN_APPROVE_PHOTO__SUCCEEDED`;
export const ADMIN_APPROVE_PHOTO_FAILED = `${category}__ADMIN_APPROVE_PHOTO__FAILED`;
export const ADMIN_APPROVE_PHOTO_RESET = `${category}__ADMIN_APPROVE_PHOTO__RESET`;

// GET POSTS
export const ADMIN_GET_POSTS_STARTED = `${category}__ADMIN_GET_POSTS__STARTED`;
export const ADMIN_GET_POSTS_SUCCEEDED = `${category}__ADMIN_GET_POSTS__SUCCEEDED`;
export const ADMIN_GET_POSTS_FAILED = `${category}__ADMIN_GET_POSTS__FAILED`;

// APPROVE POST
export const ADMIN_APPROVE_POST_STARTED = `${category}__ADMIN_APPROVE_POST__STARTED`;
export const ADMIN_APPROVE_POST_SUCCEEDED = `${category}__ADMIN_APPROVE_POST__SUCCEEDED`;
export const ADMIN_APPROVE_POST_FAILED = `${category}__ADMIN_APPROVE_POST__FAILED`;
export const ADMIN_APPROVE_POST_RESET = `${category}__ADMIN_APPROVE_POST_RESET`;

// GET PROFILE TEXTS
export const ADMIN_GET_PROFILE_TEXTS_STARTED = `${category}__ADMIN_GET_PROFILE_TEXTS__STARTED`;
export const ADMIN_GET_PROFILE_TEXTS_SUCCEEDED = `${category}__ADMIN_GET_PROFILE_TEXTS__SUCCEEDED`;
export const ADMIN_GET_PROFILE_TEXTS_FAILED = `${category}__ADMIN_GET_PROFILE_TEXTS__FAILED`;

// APPROVE PROFILE TEXTS
export const ADMIN_APPROVE_PROFILE_TEXT_STARTED = `${category}__ADMIN_APPROVE_PROFILE_TEXT__STARTED`;
export const ADMIN_APPROVE_PROFILE_TEXT_SUCCEEDED = `${category}__ADMIN_APPROVE_PROFILE_TEXT__SUCCEEDED`;
export const ADMIN_APPROVE_PROFILE_TEXT_FAILED = `${category}__ADMIN_APPROVE_PROFILE_TEXT__FAILED`;
export const ADMIN_APPROVE_PROFILE_TEXT_RESET = `${category}__ADMIN_APPROVE_PROFILE_TEXT_RESET`;

// GET PAYMENTS
export const ADMIN_GET_PAYMENTS_STARTED = `${category}__ADMIN_GET_PAYMENTS__STARTED`;
export const ADMIN_GET_PAYMENTS_SUCCEEDED = `${category}__ADMIN_GET_PAYMENTS__SUCCEEDED`;
export const ADMIN_GET_PAYMENTS_FAILED = `${category}__ADMIN_GET_PAYMENTS__FAILED`;

// APPROVE PAYMENT
export const ADMIN_APPROVE_PAYMENT_STARTED = `${category}__ADMIN_APPROVE_PAYMENT__STARTED`;
export const ADMIN_APPROVE_PAYMENT_SUCCEEDED = `${category}__ADMIN_APPROVE_PAYMENT__SUCCEEDED`;
export const ADMIN_APPROVE_PAYMENT_FAILED = `${category}__ADMIN_APPROVE_PAYMENT__FAILED`;
export const ADMIN_APPROVE_PAYMENT_RESET = `${category}__ADMIN_APPROVE_PAYMENT__RESET`;

// USER PHOTOS
export const GET_USER_PHOTOS_STARTED = `${category}__GET_USER_PHOTOS__STARTED`;
export const GET_USER_PHOTOS_SUCCEEDED = `${category}__GET_USER_PHOTOS__SUCCEEDED`;
export const GET_USER_PHOTOS_FAILED = `${category}__GET_USER_PHOTOS__FAILED`;

// GET REPORTS
export const GET_USER_REPORTS_STARTED = `${category}__GET_USER_REPORTS__STARTED`;
export const GET_USER_REPORTS_SUCCEEDED = `${category}__GET_USER_REPORTS__SUCCEEDED`;
export const GET_USER_REPORTS_FAILED = `${category}__GET_USER_REPORTS__FAILED`;

export const ADMIN_APPROVE_REPORT_STARTED = `${category}__ADMIN_APPROVE_REPORT__STARTED`;
export const ADMIN_APPROVE_REPORT_SUCCEEDED = `${category}__ADMIN_APPROVE_REPORT__SUCCEEDED`;
export const ADMIN_APPROVE_REPORT_FAILED = `${category}__ADMIN_APPROVE_REPORT__FAILED`;
export const ADMIN_APPROVE_REPORT_RESET = `${category}__ADMIN_APPROVE_REPORT_RESET`;
